import {TRADES,validate,amount,filterRows,group,quality,datesBetween,csvCell,demoData} from './model.mjs';
const $=id=>document.getElementById(id),fmt=n=>Number(n).toLocaleString('en-US',{maximumFractionDigits:2}),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const keys=['cluster','villa','area','activity','engineer'];let data,rows=[],page=0,busy=false,isDemo=true;
let apiUrl=window.DASHBOARD_CONFIG?.apiUrl||'';try{apiUrl=apiUrl||localStorage.getItem('villa-dashboard-api')||'';}catch{}
$('apiUrl').value=apiUrl;
function filters(){return Object.fromEntries(['from','to',...keys,'trade'].map(k=>[k,$(k).value]));}
function setOptions(id,values){const old=$(id).value;$(id).replaceChildren(new Option('All '+(id==='engineer'?'reporters':id==='activity'?'activities':id+'s'),''),...values.map(v=>new Option(v,v)));if(values.includes(old))$(id).value=old;}
function options(){for(const k of keys){let source=data.records;if(k==='villa'&&$('cluster').value)source=source.filter(r=>r.cluster===$('cluster').value);setOptions(k,[...new Set(source.map(r=>r[k]).filter(Boolean))].sort());}setOptions('trade',TRADES);}
function install(payload,demo){data=validate(payload);isDemo=demo;const dates=data.records.map(r=>r.date).sort();if(!$('from').value)$('from').value=dates[0]||'';if(!$('to').value)$('to').value=dates.at(-1)||'';options();page=0;render();}
function bars(id,items){const max=Math.max(0,...items.map(x=>x[1]));$(id).innerHTML=items.length?items.map(([name,n])=>`<div class="bar-row"><span class="bar-label">${esc(name)}</span><div class="track"><div class="fill" style="width:${max?Math.max(0,n)/max*100:0}%"></div></div><span class="value">${fmt(n)}</span></div>`).join(''):'<p class="empty">No records match these filters.</p>';}
function render(){if(!data)return;const f=filters();rows=filterRows(data.records,f);const uniqueVillas=new Set(rows.map(r=>r.villa).filter(Boolean));const denominator=new Set(data.villas.filter(v=>(!f.cluster||v.cluster===f.cluster)&&(!f.villa||v.id===f.villa)&&v.cluster!=='GEN').map(v=>v.id));const covered=[...uniqueVillas].filter(id=>denominator.has(id)).length;
 const cards=[['Recorded man-days',fmt(rows.reduce((s,r)=>s+amount(r,f.trade),0)),f.trade||'All six trades'],['Villas with reports',fmt(uniqueVillas.size),denominator.size?`${covered} of ${denominator.size} master villas · ${fmt(covered/denominator.size*100)}% coverage`:'No matching villa master denominator'],['Daily records',fmt(rows.length),'Source entries · not completed activities'],['Reporting users',fmt(new Set(rows.map(r=>r.engineer).filter(Boolean)).size),'Distinct reporter labels in selected records']];
 $('kpis').innerHTML=cards.map(([a,b,c])=>`<div class="kpi"><span>${esc(a)}</span><strong>${b}</strong><small>${esc(c)}</small></div>`).join('');
 const daily=group(rows,'date',f.trade).sort((a,b)=>a[0].localeCompare(b[0]));const max=Math.max(0,...daily.map(d=>d[1]));$('daily').innerHTML=daily.length?daily.map(([date,n])=>`<div class="day" title="${date}: ${fmt(n)} man-days"><b>${fmt(n)}</b><div class="daybar"><i style="height:${max?Math.max(0,n)/max*100:0}%"></i></div><span>${date.slice(5)}</span></div>`).join(''):'<p class="empty">No records match these filters. Check the date range.</p>';
 bars('trades',TRADES.filter(t=>!f.trade||t===f.trade).map(t=>[t,rows.reduce((s,r)=>s+amount(r,t),0)]));for(const [id,k,limit]of [['clusters','cluster',100],['areas','area',100],['engineers','engineer',100],['activitiesChart','activity',15]])bars(id,group(rows,k,f.trade).slice(0,limit));
 const latest=new Map();for(const r of rows.filter(r=>r.villa)){const old=latest.get(r.villa);if(!old||r.date>old.date)latest.set(r.villa,{...r,activities:new Set([r.activity])});else if(old.date===r.date)old.activities.add(r.activity);}
 $('latest').innerHTML=[...latest.values()].sort((a,b)=>b.date.localeCompare(a.date)||a.villa.localeCompare(b.villa)).map(r=>`<tr>${[r.villa,r.cluster,r.date,[...r.activities].join(' · ')].map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')||'<tr><td colspan="4">No villa records.</td></tr>';
 $('checks').innerHTML=quality(rows).map(([name,n])=>`<div class="check">${esc(name)}<strong>${n}</strong></div>`).join('');const reported=new Set(rows.map(r=>r.date));const missing=datesBetween(f.from,f.to).filter(d=>!reported.has(d));$('missingDates').textContent=missing.length?missing.join(', '):'None in this date range.';
 $('recordCount').textContent=`${fmt(rows.length)} matching records · latest dates first`;table();}
function table(){const trade=$('trade').value,sorted=[...rows].sort((a,b)=>b.date.localeCompare(a.date));const pages=Math.max(1,Math.ceil(sorted.length/50));page=Math.min(page,pages-1);$('records').innerHTML=sorted.slice(page*50,page*50+50).map(r=>`<tr>${[r.date,r.cluster,r.villa||'General / unassigned',r.area,r.activity,r.engineer||'Unassigned',...r.manDays.map(n=>n===null?'Invalid':fmt(n)),fmt(amount(r,trade))].map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')||'<tr><td colspan="13">No matching records.</td></tr>';$('pageInfo').textContent=`Page ${page+1} of ${pages}`;$('prev').disabled=page===0;$('next').disabled=page>=pages-1;$('export').disabled=!rows.length;}
function status(text,error=false){$('status').textContent=text;document.querySelector('.connection').className='connection'+(error?' error':!isDemo?' live':'');}
function safeUrl(value){const u=new URL(value);if(u.protocol!=='https:'||u.hostname!=='script.google.com'||!/^\/macros\/s\/[A-Za-z0-9_-]+\/exec$/.test(u.pathname))throw Error('Use the Apps Script HTTPS deployment URL ending in /exec.');return u.href;}
async function load(){if(busy)return;if(!apiUrl){install(demoData(),true);status('DEMO · Synthetic data — not your Google Sheet');$('updated').textContent='Connect your deployed Apps Script to load project records.';return;}busy=true;$('refresh').disabled=true;$('connect').disabled=true;status('Loading Google Sheet…');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const response=await fetch(safeUrl(apiUrl),{signal:controller.signal,redirect:'follow',credentials:'omit'});if(!response.ok)throw Error('The data endpoint returned an error.');const payload=await response.json();if(payload.error)throw Error(payload.error);install(payload,false);status('LIVE · Public read-only data');$('updated').textContent=`Retrieved ${new Date().toLocaleString()} · Sheet snapshot ${payload.generatedAt||'unknown'} · Refresh every ${window.DASHBOARD_CONFIG?.refreshMinutes||5} minutes`;}catch(e){status(`Connection failed. ${data?'Previously loaded '+(isDemo?'demo':'project')+' data remains visible. ':''}${e.name==='AbortError'?'Request timed out.':e.message}`,true);$('updated').textContent='Check deployment access is Anyone, execution is as owner, and the URL ends in /exec. No new data loaded.';}finally{clearTimeout(timer);busy=false;$('refresh').disabled=false;$('connect').disabled=false;}}
for(const k of ['from','to',...keys,'trade'])$(k).addEventListener('change',()=>{if(k==='cluster')options();page=0;render();});
$('reset').onclick=()=>{for(const k of ['from','to',...keys,'trade'])$(k).value='';install(data,isDemo);};$('prev').onclick=()=>{page--;table();};$('next').onclick=()=>{page++;table();};$('refresh').onclick=load;
$('connect').onclick=()=>{try{apiUrl=safeUrl($('apiUrl').value.trim());try{localStorage.setItem('villa-dashboard-api',apiUrl);}catch{}$('from').value='';$('to').value='';load();}catch(e){status(e.message,true);}};
$('demo').onclick=()=>{if(busy)return;apiUrl='';$('apiUrl').value='';try{localStorage.removeItem('villa-dashboard-api');}catch{}for(const k of ['from','to',...keys,'trade'])$(k).value='';load();};
for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>{for(const n of document.querySelectorAll('[data-view]')){n.classList.toggle('active',n===b);n.setAttribute('aria-pressed',String(n===b));}for(const v of document.querySelectorAll('.view'))v.hidden=v.id!==b.dataset.view;};
$('export').onclick=()=>{const head=['Log ID','Date','Cluster','Villa','Area','Activity','Engineer',...TRADES.map(t=>t+' man-days'),'Selected-trade man-days'];const lines=[head,...rows.map(r=>[r.id,r.date,r.cluster,r.villa,r.area,r.activity,r.engineer,...r.manDays,amount(r,$('trade').value)])];const blob=new Blob(['\uFEFF'+lines.map(line=>line.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(isDemo?'demo-':'')+'villa-manpower.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
await load();setInterval(()=>{if(apiUrl&&!document.hidden)load();},Math.max(1,Number(window.DASHBOARD_CONFIG?.refreshMinutes)||5)*60000);
